# Generated by Django 4.2.3 on 2023-07-08 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="age",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="how_much_invest",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="how_much_per_month",
            field=models.CharField(default="0", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="how_much_wish",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="insta_handler",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
        migrations.AddField(
            model_name="booking",
            name="obstacle",
            field=models.CharField(default="SOME STRING", max_length=100),
        ),
    ]
